env: "local"
connection_string: "postgres://postgres:1234@localhost:5432/voronkadb?sslmode=disable"
token_ttl: 24

server:
    addres: "localhost"
    port: 8080
    timeout: 10h

redis:
    host: "localhost"
    port: 6379

